### PR TITLE
Wrap marker around periodic boundaries

### LINKED ISSUE #2: Mesh adapativity not working with periodic boundary conditions
Distance check here is just the raw distance:
https://github.com/jessecarterMOOSE/PRARIEDOG/blob/master/src/markers/EventMarker.C#L61

Need to use MooseMesh::minPeriodicDistance but will need to inherit from Coupleable. See GaussianUserObject:
https://github.com/jessecarterMOOSE/PRARIEDOG/blob/master/src/userobjects/GaussianUserObject.C#L40
https://github.com/jessecarterMOOSE/PRARIEDOG/blob/master/include/userobjects/GaussianUserObject.h#L35

### PR DESCRIPTION
**Pull request by jessecarterMOOSE**
Distance to event can now be minPeriodicDistance, needs user to supply a periodic variable.

Added test.

Fixes #2

### CODE REVIEW

File: include/markers/EventMarker.h [hunk 1]
```diff
@@ -18,6 +18,7 @@
 #include "Marker.h"
 #include "EventInserter.h"
 #include "GaussianUserObject.h"
+#include "Coupleable.h"
```
Comment (jessecarterMOOSE) [inline include/markers/EventMarker.h]: Getting tired of adding the Coupleable interface to everything. Wonder if there is a better way to do this.

File: include/markers/EventMarker.h [hunk 2]
```diff
@@ -27,7 +28,7 @@ class EventMarker;
 template<>
 InputParameters validParams<EventMarker>();
 
-class EventMarker : public Marker
+class EventMarker : public Marker, public Coupleable
```
Comment (jessecarterMOOSE) [inline include/markers/EventMarker.h]: Getting tired of adding the Couleable interface to everything. Wonder if there is a better way to do this.

**Comment by jessecarterMOOSE** [comment]
Looks good. :+1:
